### ISSUE TITLE
[TASK]: Create index file in components folder.

### ISSUE THREAD

**Issue by Lukortech** [webdevcody/code-racer#110]
### Task Summary

Take care of the `src/components/ui` folder and create an index file from which the components could be imported. 
That way we'll have em all in one spot and allow ourselves to use _jspath_  to import from `@components/Button`.

### Acceptance criteria

- [ ] Add components to paths in tsconfig file

![image](https://github.com/webdevcody/code-racer/assets/26508593/266db6bf-15aa-4c6a-bd52-ac3ffd993715)

- [ ] Create index file that imports and re-exports all the files in said folder.

**Comment by webdevcody** [comment]
sorry, I personally do not like index files that import / export files; I'm using my privilege to overrule
