### ISSUE TITLE
[BUG]: Typing requires extra spaces

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/code-racer#127]
### Description

When typing the snippet, you often need to press extra spaces after pressing enter for going to the next line.  I think the editor should automatically process the cursor to the next character after you press enter.  Requiring a user to press space 4 times to indent is a bit annoying for a speed typing app.

### Reproduction Steps

just try typing, you'll see how annoying it is

### Expected Behaviour

it should feel better

### Actual Behaviour

too many required fields on this bug report

### Operating System / Platform

Mac (iOS)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudo-adduser-jordan** [comment]
Assigning this to myself.
