### ISSUE TITLE
[FEATURE]: Show Other's top 10 Results for snippet

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/code-racer#129]
### Feature Summary

After finishing racing on a snippet, the results page should show the top 10 racers for that snippet and allow users to click into their profile.

### Acceptance criteria

- [ ] user can view top 10 users who raced on this snippet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RobinVW** [comment]
I want to try this one

**Comment by scape76** [comment]
> I want to try this one
any updates? Maybe you need some help?

**Comment by RobinVW** [comment]
Gonna work on this today, had no time yesterday. If I need help I let you know!
