### ISSUE TITLE
[FEATURE]: Link to Snippet on Dashboard

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/code-racer#130]
### Feature Summary

change game id to snippet id, and allow the user to click that snippet id to take them back to the race page with that snippet loaded for them to race again with.

### Acceptance criteria

- [ ] a user shall be able to race against a snippet from clicking the snippet id in their dashboard

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mshubitidze** [comment]
I'll work on this
