### ISSUE TITLE
[FEATURE]: Badge for uploading first snippet

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/code-racer#132]
### Feature Summary

a user should get a badge after uploading their first snippet
the user shall see a toast and confetti pop up after they upload their first snippet.  
this badge should display on their profile page.

### Acceptance criteria

^ see above

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mauryapari** [comment]
Assigning this to myself.
