### ISSUE TITLE
[FEATURE]: Leaderboard should show profile stats, not individual race stats

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/code-racer#134]
### Feature Summary

When viewing the leader board, it shows EVERY race result entry, but instead we should only be showing the overall information related to a user's average CPM and points.

### Acceptance criteria

- see above

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by trace2798** [comment]
I think it will be better if both exist. A card somewhere on the page to show the overall points and stuff and the table for everything. What do you think about it?

**Comment by scape76** [comment]
I want to work on this

**Comment by scape76** [comment]
Whats the points? How user should achieve it?

**Comment by trace2798** [comment]
@scape76 For the card?
