### ISSUE TITLE
[FEATURE]: Badge when finishing your first race

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/code-racer#137]
### Feature Summary

After a user finishes their first race, we should give then an achievement (prisma models already exist and are displayed in profile)

Show confetting on the page after giving the badge

Show a toast after earning the badge that has a link to your badges on your profile.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mshubitidze** [comment]
assign this to myself
