### ISSUE TITLE
[TASK]: Add success / error notifications if form submitting was successful

### ISSUE THREAD

**Issue by masterHAWK99** [webdevcody/code-racer#146]
### Task Summary

There should be at least simple form validation (e.g. checking for empty fields) and success / error notifications if submitting was successful or not.

**Comment by CallMeJSON** [comment]
I will try some client-side validation and hope for the best :)

**Comment by CallMeJSON** [comment]
to check if textarea is empty can be easy fixed with (?):     
if  (codeSnippet == '') return; 

what kind of condition for succes and error do you reckon we need?

**Comment by AVAniketh0905** [comment]
> to check if textarea is empty can be easy fixed with (?): if (codeSnippet == '') return;
> 
> what kind of condition for succes and error do you reckon we need?

maybe an popup to redirect to race page

**Comment by trace2798** [comment]
@CallMeJSON How is this going? If you need help adding toast let me know. I know how to add toast and embed a link to the race page.

**Comment by AVAniketh0905** [comment]
im going to pick this up @trace2798

**Comment by trace2798** [comment]
@AVAniketh0905 just was this notification. Good work
