### ISSUE TITLE
[BUG]: Arrow Keys Are Not Tracked Properly

### ISSUE THREAD

**Issue by Ragudos** [webdevcody/code-racer#169]
### Description

So, this is definitely impacting user experience as I myself get frustrated when I try to play. The arrow keys are not being tracked, but they should be just as it would in a terminal or command-line.

### (optional) What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ragudos** [comment]
Assigning myself to this

**Comment by sudo-adduser-jordan** [comment]
Please wait until #172 has been merged. Arrow keys will need to be disabled.

**Comment by sudo-adduser-jordan** [comment]
#172 has been merged.

**Comment by vignesh-gupta** [comment]
@scape76 this one to @Ragudos

**Comment by laroccol** [comment]
This pr overwrote some of the follower changes. Was this intentional?
