### ISSUE TITLE
[FEATURE]: Add error checks to Add snippet page

### ISSUE THREAD

**Issue by Psypher1** [webdevcody/code-racer#176]
### Feature Summary

Checks to be made to make sure a snippet has correct data before it is added

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FlorjanKlancar** [comment]
Can I work on this?

**Comment by scape76** [comment]
> Can I work on this?

yes, assigned this to you

**Comment by vignesh-gupta** [comment]
@FlorjanKlancar I think it is done, isn't it @scape76 ?
