### ISSUE TITLE
[BUG]: Can copy and paste the same code

### ISSUE THREAD

**Issue by saranshhardaha** [webdevcody/code-racer#180]
### Description

I am able copy and paste the same snippet code and able to complete around 2 sec.

Steps to recreate..
- You can just copy and paste the code from the UI.

Screenshot
![image](https://github.com/webdevcody/code-racer/assets/37737242/fd2f5944-44a2-4a54-ad78-7842b38099cf)

### (optional) What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by trace2798** [comment]
I will look into it

**Comment by trace2798** [comment]
@BumpyPlayz I just fixed it. Check my PR and if you want to add or change anything feel free tho
