### ISSUE TITLE
[FEATURE]: New Line Feedback

### ISSUE THREAD

**Issue by alifhaider** [webdevcody/code-racer#182]
### Feature Summary

Currently pressing `Enter` key doesn't provide any UI feedback. Maybe, we can add `↩` key to a new line and put the cursor over there to let the user know, line break is needed and `Enter` key is pressed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudo-adduser-jordan** [comment]
This issue will be closed in #172
