### ISSUE TITLE
[FEATURE]: Allow backspace on typing

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/code-racer#185]
### Feature Summary

- users should NOT be able to finish the race if they have errors
- every time a user types the wrong character, count that against their accuracy
- users should be able to backspace to correct their mistakes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudo-adduser-jordan** [comment]
Assigning myself to this issue.

**Comment by vignesh-gupta** [comment]
Hey @sudo-adduser-jordan  how is it coming along?

**Comment by sudo-adduser-jordan** [comment]
Good. I will submit a PR later today.

**Comment by vignesh-gupta** [comment]
Great looking forward to it because I got annoyed by this today!

**Comment by vignesh-gupta** [comment]
@scape76 could you please assign this one to @sudo-adduser-jordan

**Comment by sudo-adduser-jordan** [comment]
Complete:
- Error++ for each miss.
- Backspace enabled.
- Now can navigate text successfully

https://github.com/webdevcody/code-racer/assets/108599131/5c61246e-698f-4054-8f6a-0da19c392caf

TODO: 
- Resolve merges
- Add check for race completion without errors
- Tidy up
- Video

**Comment by vignesh-gupta** [comment]
As the feature is completed. 
Please Close this issue. @scape76
