### ISSUE TITLE
[FEATURE]: Design Multiplayer Racing aspect

### ISSUE THREAD

**Issue by mauryapari** [webdevcody/code-racer#192]
### Feature Summary

Allow multiple users to participate in a single race and show the performance of each player on the screen. Once someone completes the snippet, redirect all users to the result page.

*will implement extra things when it comes to mind.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mauryapari** [comment]
Assigning this to myself

**Comment by scape76** [comment]
At this point we will need to use websockets / or some technology that provides their own servers like pusher.com

**Comment by greidinger-reis** [comment]
Why not supabase-realtime ? we're already using postgres

**Comment by scape76** [comment]
@webdevcody what do you think?
