### ISSUE TITLE
Create a Landing Page

### ISSUE THREAD

**Issue by sleman-safiah** [webdevcody/code-racer#20]
- [ ] Add some info to the race page
- [ ] Add some links to the race page

**Comment by liamsegura** [comment]
Can i be assined this?

**Comment by mauryapari** [comment]
Please assign this to me. I am already working on it.
Thanks

**Comment by webdevcody** [comment]
@mauryapari @liamsegura please respond if you're working on this, if not I'm going to find someone else

**Comment by mauryapari** [comment]
Hey. @webdevcody. I am working on this.
