### ISSUE TITLE
[TASK]: Consistency on file naming

### ISSUE THREAD

**Issue by greidinger-reis** [webdevcody/code-racer#200]
### Task Summary

I just would like to point out that 90% of the codebase is using kebab-case as file name convention, but there is a little camelCase here and there, I know it's a whatever issue, but it's good to keep consistency in the codebase I think.

examples:

`src/app/race/racePositionTracker.tsx`
`src/app/race/typingCode.tsx`
`src/app/race/displayedCode.tsx`
`src/app/race/noSnippet.tsx`

Should we care about this, or just let people with OCD suffer? 🤣

**Comment by scape76** [comment]
let's keep it in kebab-case for components

**Comment by scape76** [comment]
do you want to work on this?

**Comment by greidinger-reis** [comment]
Yeah, sure I'll post a PR
