### ISSUE TITLE
[FEATURE]: Real data on result page

### ISSUE THREAD

**Issue by scape76** [webdevcody/code-racer#212]
### Feature Summary

![image](https://github.com/webdevcody/code-racer/assets/87383867/3dc38493-134c-4a1e-9be3-b52612f88907)
Show the real data based on the race result

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mauryapari** [comment]
@scape76 . if you are not working on it. can i asign it me?

**Comment by scape76** [comment]
> @scape76 . if you are not working on it. can i asign it me?

assigning to you
