### ISSUE TITLE
[BUG]: 404 page for result page - Guest Users

### ISSUE THREAD

**Issue by vignesh-gupta** [webdevcody/code-racer#228]
### Description

Post completing the typing i.e. on result page it says 404
[Screencast from 2023-07-14 23-10-05.webm](https://github.com/webdevcody/code-racer/assets/52371759/21c56344-0d69-4025-aca4-bce679bad11f)

### (optional) What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TyrinH** [comment]
Can I work on this issue?

**Comment by vignesh-gupta** [comment]
Sure @TyrinH !

**Comment by TyrinH** [comment]
@vignesh-gupta It looks like we don't check to make sure you are logged in as an existing user when Router.push fires to send the page to the snippet they just completed. How should that work if you are a guest? Should the router instead push back to the landing page?

**Comment by vignesh-gupta** [comment]
I think it's better if we show a toast saying,  `please login to add snippet` and keep the user on the same page

**Comment by TyrinH** [comment]
I think I got it working the way you're thinking, I wrote the toast to say save your result instead of add snippet since this is after the race is completed. Would you like me to send a video before opening a PR?
<img width="1511" alt="Screen Shot 2023-07-14 at 3 26 40 PM" src="https://github.com/webdevcody/code-racer/assets/11969924/1d74c390-684e-4889-9681-65d1ae96b2b2">

**Comment by vignesh-gupta** [comment]
No need to send video you can attach that in You PR. But for some reason that's does looks good to me from UX perspective. Can we show them results  and then on that's page show the same as warn

 @scape76 do you have any suggestions here?

**Comment by TyrinH** [comment]
You are saying we should show the result of the race and then instead of red toast show a yellow or a warning colored toast?

**Comment by scape76** [comment]
At first it was intended to show the result of a race even if user is not authorized. If he is, the result is also stored in the db

**Comment by TyrinH** [comment]
@scape76 do we want to keep that functionality and still show the results page then and just use a toast to suggest that the guest should sign in to save their results?

**Comment by scape76** [comment]
> @scape76 do we want to keep that functionality and still show the results page then and just use a toast to suggest that the guest should sign in to save their results?

yeah, that would be good

**Comment by vignesh-gupta** [comment]
> @scape76 do we want to keep that functionality and still show the results page then and just use a toast to suggest that the guest should sign in to save their results?
Yeah @TyrinH , I think that would be good to have

**Comment by TyrinH** [comment]
Would it be better to just place text in the page that says the same thing instead of a toast? That way it's always there? I'm open to changing up the styling?
<img width="1510" alt="Screen Shot 2023-07-15 at 9 15 59 AM" src="https://github.com/webdevcody/code-racer/assets/11969924/d097908f-1e5d-4090-8b90-2b7cc5807386">

**Comment by TyrinH** [comment]
@scape76 Can I get your thoughts on this?

**Comment by scape76** [comment]
personally I would not even show  "Sign in to..."

**Comment by scape76** [comment]
Or I would show the feature, and when a user clicks on an upvote/downvote button, it sends a toast message saying "You should sign in first"

**Comment by TyrinH** [comment]
> Or I would show the feature, and when a user clicks on an upvote/downvote button, it sends a toast message saying "You should sign in first"

Makes sense, I'll go with that approach I'll need to figure out how to show the feature even if the user isn't signed in since the component is expecting a user.id

**Comment by TyrinH** [comment]
@scape76  How this? It doesn't seem like we have a more warning type of color unless we're using variant middle for that?
<img width="1510" alt="Screen Shot 2023-07-15 at 11 04 24 AM" src="https://github.com/webdevcody/code-racer/assets/11969924/71741722-c28e-4753-affe-c2c972128120">

**Comment by TyrinH** [comment]
#278

**Comment by vignesh-gupta** [comment]
Identify and clean as well. Great job @TyrinH !

**Comment by vignesh-gupta** [comment]
@TyrinH Since dev is done. Closing this issue.
