### ISSUE TITLE
[TASK]: Fix Unwanted scrolling and footer should be in the bottom 

### ISSUE THREAD

**Issue by vignesh-gupta** [webdevcody/code-racer#230]
### Task Summary

In some pages ( landing , Leaderboard , Add Snippet) the footer is not stick to the bottom and in some (Race, profile) pages there is extra heigth. 
[Screencast from 2023-07-14 23-18-27.webm](https://github.com/webdevcody/code-racer/assets/52371759/d51f9bd4-3156-4c8e-9fa8-2ca2aeae05ce)

**Comment by vignesh-gupta** [comment]
Started working on it. Will create a PR soon!

**Comment by scape76** [comment]
@vignesh-gupta did you fix the scrolling or just buttons?

**Comment by vignesh-gupta** [comment]
Both are fixed now!
