### ISSUE TITLE
[FEATURE]: Use next-safe-action instead of zact

### ISSUE THREAD

**Issue by greidinger-reis** [webdevcody/code-racer#240]
## Why?
- [next-safe-action](https://github.com/TheEdoRan/next-safe-action) is a much better mantained package, with more features, such as easy auth-only action
- Even Theo on one of his stream's looked at it and said it's probably better to use it instead.
- [zact](https://github.com/pingdotgg/zact) last commit: 2 months ago
- [next-safe-action](https://github.com/TheEdoRan/next-safe-action) last commit: yesterday

I can do this refactor, if we agree to change.

[example app with this lib implemented](https://github.com/TheEdoRan/next-safe-action/tree/main/packages/example-app)
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vignesh-gupta** [comment]
Hey @greidinger-reis if you are not picking anything. Feel free to update it and create a PR then @webdevcody or @scape76 can look into it. Sounds good?

**Comment by greidinger-reis** [comment]
Sure, I will refactor it.
