### ISSUE TITLE
[BUG]: Creating a page for privacy.

### ISSUE THREAD

**Issue by trace2798** [webdevcody/code-racer#251]
### Description

Since users can log in we need to create a page for a privacy policy as @VoidedName has mentioned on #250 which is related to #246.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by trace2798** [comment]
I am creating the layout for privacy page

**Comment by VoidedName** [comment]
(i swear, one day i will not assign myself by accident...)

**Comment by trace2798** [comment]
@VoidedName I have added a page route for privacy (/privacy) and created a new component called subheading too. So feel free to make any changes you want.

**Comment by trace2798** [comment]
@VoidedName I am closing this issue and creating a new one for the content for privacy.
