### ISSUE TITLE
[FEATURE]: Show Result for anonymous users

### ISSUE THREAD

**Issue by mauryapari** [webdevcody/code-racer#272]
### Feature Summary

Make sure we show race results for a user who has not logged in to the website. 

*we could try storing the result in local storage or passing it by query params.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mauryapari** [comment]
Working on it.

**Comment by plbstl** [comment]
@mauryapari i would love to work on this with you, if you can

**Comment by mauryapari** [comment]
hi @plbstl . you can take it up. I have created a PR for showing real data on the result page.
https://github.com/webdevcody/code-racer/pull/307
let me know if you have any questions.

**Comment by mauryapari** [comment]
Hi @plbstl. let me know if you have started something. we can connect. For now, I am also working on it.

**Comment by plbstl** [comment]
okay. i just sent you a request on discord

**Comment by mauryapari** [comment]
hey @webdevcody. sorry, I am a bit busy this week. Please assign this to someone else. Thanks
