### ISSUE TITLE
[FEATURE]: Post Bio & display on user profile

### ISSUE THREAD

**Issue by mmcbride2929** [webdevcody/code-racer#274]
### Feature Summary

> Users need to be able to save changes when editing their bio, on their profile page. Once their bio has been saved, it should be visible to other users when viewing their page
> 
> * [ ]  when a user clicks "save changes" via the "Add Bio" modal on the user's profile, the input's value should be added to db.
> * [ ]  When visiting a users profile page, if they have a bio, their bio should be fetched and displayed.
> 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mmcbride2929** [comment]
I will be requesting a change to the prisma schema, allowing bio's to be posted to the db, and then taking care of this ticket.

**Comment by mmcbride2929** [comment]
Can I please be unassigned from this? I need to continue learning nextjs before I'll be able to finish this

**Comment by vignesh-gupta** [comment]
I think now we have this feature @mmcbride2929. You can close this issue.

@scape76
