### ISSUE TITLE
Cant sign in 

### ISSUE THREAD

**Issue by salmansheri** [webdevcody/code-racer#276]
Cannot sign in to app 
![coderacer](https://github.com/webdevcody/code-racer/assets/95226945/4e239ae8-6f73-4e9f-9ab7-5663f9b72fdd)

**Comment by plbstl** [comment]
does it show the connect github app page?

**Comment by salmansheri** [comment]
yes

**Comment by WillsWebsites** [comment]
Same for me, tried hard refresh and clearing session cookies but no luck

**Comment by sudo-adduser-jordan** [comment]
I am able to login with the updated repository.

Please include more information:
1. Are you logining in locally or in the publicly hosted website?
2. Error logs if applicable

If you are having issues:
1. Verify you are up to date - your fork has been synced and any conflicts resolved
2. Check in with discord
3. Delete project
4. Clear everything in Docker using:
 - https://hub.docker.com/extensions/docker/disk-usage-extension
5. Re install project

**Comment by WillsWebsites** [comment]
This is on the Vercel publicly hosted website for me. Is it currently blocked except for specific users?

**Comment by salmansheri** [comment]
ERROR IN PUBLICLy hosted website

**Comment by vignesh-gupta** [comment]
@salmansheri this was a cred issue. Which has been fixed on prod. Please close the issue.

@scape76
