### ISSUE TITLE
[BUG]: Race is stuck when I finish

### ISSUE THREAD

**Issue by joesabbagh1** [webdevcody/code-racer#280]
### Description

I completed the race but it seems its stuck and not redirecting me to see the results

<img width="1147" alt="Screen Shot 2023-07-15 at 7 46 06 PM" src="https://github.com/webdevcody/code-racer/assets/70956839/45fe372e-5838-4581-a160-11ca49ff6281">

This issue appeared when i synced my fork btw, so something recently broke it

### (optional) What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joesabbagh1** [comment]
I'll be working on it

**Comment by sudo-adduser-jordan** [comment]
I put an intentional block on it for debugging purposes while I was working with the cursor. I pushed my changes to main so others have a chance to work on it while I'm busy. We now need to verify the errors and outputs. I will work on it once I have some free time. I will check in before I do.

**Comment by sudo-adduser-jordan** [comment]
I also added locations for arrow key functions to be implemented. I saw there is another issue to add arrow key support. There will likely be some refactoring involved.

**Comment by joesabbagh1** [comment]
you mean the '\n', yeah i removed it but now, im getting this error 
'Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.' 
Trying to fix it

**Comment by joesabbagh1** [comment]
solved it, endTime was a useEffect dependency and you were setting a new time in the useEffect, idk if it was you but yeah
