### ISSUE TITLE
[BUG]: special buttons click cause unwanted behaviour

### ISSUE THREAD

**Issue by scape76** [webdevcody/code-racer#287]
### Description

When I am clicking on capslock / tabs / shift buttons, it causes unwanted behaviour (it types in some
characters, but what I want is:

1. on tabs produce 2 spaces
2. on caps lock I don't want it to produce anything at all
3. on shift same as 2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudo-adduser-jordan** [comment]
Assigning myself to this issue.
