### ISSUE TITLE
Create Dashboard Page

### ISSUE THREAD

**Issue by harmochiky** [webdevcody/code-racer#29]
Users can get an overview of their activity sucha as history for races or completed challenges, perfomance metrics and progress tracking which will come to award badges in return based on the perfomance. This will allow users to mornitor and track improvement. _Might highly likely work on data visualization aswell_

Features
- [ ] Race history
- [ ] Perfomance metrics
- [ ] Progress tracking (can be over time)
- [ ] Achievements and badges

**Comment by Killbyfire** [comment]
I'll work on this I guess

**Comment by harmochiky** [comment]
I'm on it as well.

**Comment by webdevcody** [comment]
we have a decent dashboard page, closing
