### ISSUE TITLE
[BUG]: Word shifting on home page load

### ISSUE THREAD

**Issue by WillsWebsites** [webdevcody/code-racer#291]
### Description

When you load the home page originally or on refresh the wording shifts on the hero section and then settles into the correct position. See attached image.

<img width="1617" alt="Screenshot 2023-07-15 at 6 47 43 PM" src="https://github.com/webdevcody/code-racer/assets/108106876/250b3684-5b39-4f6d-a586-212717aedc87">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Brodypen** [comment]
I would love to work on this!
