### ISSUE TITLE
[TASK]: Verify race result outputs

### ISSUE THREAD

**Issue by sudo-adduser-jordan** [webdevcody/code-racer#292]
### Race result outputs need to be verified they are correct.

Working directory:  `/src/app/race/race.tsx` 

### This [ Task ] should be done when editing any logic inside this directory.

Consider adding tests:
- timeTaken
- errors
- cpm
- accuracy

### Issue Labels:
- [HIGH PRIORITY] 
- [TASK] 
- [BUG]

**Comment by Yuhannakapali** [comment]
we don't have test setup so i guess we have to setup test suite first.
