### ISSUE TITLE
[TASK]: Pass user selected language to /practice for better UX / userflow

### ISSUE THREAD

**Issue by mahtaraatwit** [webdevcody/code-racer#298]
### Task Summary

When user selects language, hits Practice, and has no new snippets, it would make sense that the next page tells them that there is "No (lang selected) snippet found) and to Create New (lang selected) snippet

Once clicked create, language is by default selected to their (lang selected) by default

This is shown below in the gif

https://github.com/webdevcody/code-racer/assets/66905824/0814edd6-2a1a-4ef8-84a2-0d97596bb115

**Comment by Yuhannakapali** [comment]
ok let me work on it

**Comment by phoukiethseng** [comment]
Cool. You can create a PR for that

**Comment by Yuhannakapali** [comment]
[Pr]( https://github.com/webdevcody/code-racer/pull/301)has been created hope it get accepeted by maintainer.
