### ISSUE TITLE
Create DockerFile / docker-compose 

### ISSUE THREAD

**Issue by sudo-adduser-jordan** [webdevcody/code-racer#3]
Acceptance criteria:

  - [ ] DockerFile
  - [ ] docker-compose w/ Postgres
  - [ ] .dockerignore

**Comment by webdevcody** [comment]
I'd say let's try to use postgres inside the docker-compose since we'll probably deploy somewhere which uses postgres

**Comment by sudo-adduser-jordan** [comment]
Issue updated from SQLite to Postgres.

**Comment by icep0ps** [comment]
submitted a PR for this
