### ISSUE TITLE
[FEATURE]: Display Race Timer

### ISSUE THREAD

**Issue by phoukiethseng** [webdevcody/code-racer#300]
### Feature Summary

User should be able to see race timer when they start typing.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by phoukiethseng** [comment]
I'll be working on this

**Comment by WillsWebsites** [comment]
I made a RaceDetails component that lives at the bottom of the race component. Maybe it could live in there? It's on issue #303 rn though, still trying to push it up.

**Comment by phoukiethseng** [comment]
> I made a RaceDetails component that lives at the bottom of the race component. Maybe it could live in there? It's on issue #303 rn though, still trying to push it up.

Sorry I didn't reply earlier, I was about to create a PR for it. You can refactored my code to your component once I my PR merged. What do you think?

**Comment by WillsWebsites** [comment]
@phoukiethseng All good, I did just send up a PR for it we can get them merged later perhaps
