### ISSUE TITLE
[TASK]:  Show submitting state when practice race is submitting

### ISSUE THREAD

**Issue by WillsWebsites** [webdevcody/code-racer#303]
### Task Summary

Have a loading spinner below the code block when the results are being submitted for better user feedback

**Comment by WillsWebsites** [comment]
I would like to do this one

**Comment by WillsWebsites** [comment]
I already have this completed

**Comment by vignesh-gupta** [comment]
@WillsWebsites If you have completed please create a PR.

**Comment by WillsWebsites** [comment]
@vignesh-gupta Just sent that up
