### ISSUE TITLE
Add .env to gitignore

### ISSUE THREAD

**Issue by BrunchWithYou** [webdevcody/code-racer#31]
We need to add .env to gitignore so people don't upload it in their pull requests.

**Comment by BrunchWithYou** [comment]
How can I assign this to myself?

**Comment by harmochiky** [comment]
Did you manage to run the db ?, please assist with setup harmony@entrebyte.co.za or reply here

**Comment by BrunchWithYou** [comment]
> Did you manage to run the db ?, please assist with setup [harmony@entrebyte.co.za](mailto:harmony@entrebyte.co.za) or reply here

I was able to run it after creating a free db from railway and pasting in their variables. However, I was recommended to use docker. So now I am still figuring out how to do that and is currently downloading docker and reading up on it as I am new to docker. So yes and no

**Comment by BrunchWithYou** [comment]
> Did you manage to run the db ?, please assist with setup [harmony@entrebyte.co.za](mailto:harmony@entrebyte.co.za) or reply here

I just got docker running and was able to run db. Still got the steps fresh in my head and could maybe help someone else with setup if they are running windows. Should we add this to original readme or the contributing readme that cody created an issue for?

**Comment by harmochiky** [comment]
Please do assist, i use linux ubuntu but setup could be the same you could also add to the contributing readme, I'm sure that could definitely help more people like me. Thank you 🤝

> > Did you manage to run the db ?, please assist with setup [harmony@entrebyte.co.za](mailto:harmony@entrebyte.co.za) or reply here
> 
> 
> 
> I just got docker running and was able to run db. Still got the steps fresh in my head and could maybe help someone else with setup if they are running windows. Should we add this to original readme or the contributing readme that cody created an issue for?
