### ISSUE TITLE
[BUG]: CapsLock press moves the cursor forward in race

### ISSUE THREAD

**Issue by mauryapari** [webdevcody/code-racer#313]
### Description

While typing in a race, if I press on CapsLock button, the cursor is pushed forward by multiple characters. 

[CAPSLOCK ISSUE.webm](https://github.com/webdevcody/code-racer/assets/47924620/b677fa9d-ff9d-4252-bab2-aa96bda7d46c)

### (optional) What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mauryapari** [comment]
working on it.

**Comment by Ragudos** [comment]
Hello, this should be fixed by a simple e.preventDefault(). Please do add them  in the noopKeys variables.
