### ISSUE TITLE
[BUG]: Certain snippets cause extra spaces

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/code-racer#340]
### Description

The following snippet causes multiple extra spaces after the <div> row.  Load this snippet and just try typing it correctly, you'll see it add a bunch of extra spaces at some point.

```
const Page = () => {
return (
<div> Hello </div>
) 
}
```

I think the bug is inside the Enter function of the src/app/race/race.tsx file.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by scape76** [comment]
As I copy this code, I see extra spaces after the ) character on the row before the last one. I think that causes an issue. To prevent uploading snippets like this we can go through the snippet and on each row remove all the spaces from the end until there is a character

**Comment by scape76** [comment]
I will try to fix this

**Comment by sudo-adduser-jordan** [comment]
@scape76  #349
