### ISSUE TITLE
[BUG]: Total errors doenst reset on restart

### ISSUE THREAD

**Issue by scape76** [webdevcody/code-racer#357]
### Description

Total errors count should be resetted on restart

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by suti1979** [comment]
Can i fix this?

**Comment by suti1979** [comment]
https://github.com/webdevcody/code-racer/pull/361

**Comment by sudo-adduser-jordan** [comment]
This issue can be marked as closed.
