### ISSUE TITLE
[FEATURE]: Store user's coding language 

### ISSUE THREAD

**Issue by mmcbride2929** [webdevcody/code-racer#365]
### Feature Summary

We need to store the user's coding language after they select one so that they can avoid having to take an extra step to select a coding language every time they'd like to play. Each time they change the language, the db will reflect that.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mmcbride2929** [comment]
Will work on this

**Comment by Littletonconnor** [comment]
@mmcbride2929 Still working on this? Otherwise i'd be happy to pick it up.

**Comment by mmcbride2929** [comment]
@Littletonconnor shes all yours

**Comment by sudo-adduser-jordan** [comment]
This feature has been implemented. This issue can be marked as closed.
