### ISSUE TITLE
[TASK]: Updated the toast for FIRST_SNIPPET Achievement 

### ISSUE THREAD

**Issue by vignesh-gupta** [webdevcody/code-racer#374]
### Task Summary

Updated the toast for FIRST_SNIPPET Achievement to look like FIRST_RACE Achievement to keep the design standardized.

FIRST_SNIPPET achivement
![Screenshot from 2023-07-17 21-24-33](https://github.com/webdevcody/code-racer/assets/52371759/e42e8805-91d3-43cd-b448-628bdd7ada17)

FIRST_RACE Achievement
![Screenshot from 2023-07-17 21-34-24](https://github.com/webdevcody/code-racer/assets/52371759/35d8df95-d938-4cb5-b525-972ee0c1b067)

**Comment by scape76** [comment]
> hey can I work on this?

of course

**Comment by vignesh-gupta** [comment]
> 

Sure please!

**Comment by kos3nz** [comment]
> hey can I work on this?

Hey are you still working on this one? I'd love to take over if you don't mind!

**Comment by FlorjanKlancar** [comment]
Yes I didn't find the time to start working on that. Feel free to take over.

**Comment by vignesh-gupta** [comment]
@kos3nz the PR you create I think we should show it whenever the any achievement is unlocked and about this issue the idea it to follow the same design for both achievements toast

**Comment by vignesh-gupta** [comment]
If you have not started do let me know I'll work on it.

**Comment by kos3nz** [comment]
@vignesh-gupta Yes I fixed it and now confetti and achievement toasts will show up whenever we want to. Thanks though!

**Comment by vignesh-gupta** [comment]
LGTM! Thanks @kos3nz.
