### ISSUE TITLE
[FEATURE]: Cursor click to position in race code snippet

### ISSUE THREAD

**Issue by WillsWebsites** [webdevcody/code-racer#383]
### Feature Summary

Be able click anywhere in the code snippet and have the cursor go there to make adjustments. That way if you make a mistake and didn't realize you can go back to it and edit it, just how a regular code editor would work.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xdguido** [comment]
maybe this could be solved implementing `Ctrl + Arrows` to jump words with the cursor

**Comment by sudo-adduser-jordan** [comment]
This would require quite the refactor. I would like to take the easy route above. Also, this being a keyboard application, I feel that being able to click within the input would be cheating. Other applications don't allow this functionality.

**Comment by sudo-adduser-jordan** [comment]
This would requrie an extensive refactor. I would like to use the solution suggested above. Similar applications do not allow this functionality.

**Comment by sudo-adduser-jordan** [comment]
#394
