### ISSUE TITLE
Prisma Schema conventions

### ISSUE THREAD

**Issue by acollierr17** [webdevcody/code-racer#39]
Hello!

I suggest we follow a few conventions with the [Prisma schema](https://github.com/webdevcody/code-racer/blob/0ad8a4258467e55ff9d81d7e3da316a519cbcd67/prisma/schema.prisma) with Postgres and, generally, a SQL database/dialect.

### `@map` attribute
Using the [`@map`](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#map) attribute, any fields named in the schema using `camelCase` should be mapped to their respective column name using `snake_case`.

For example, with #37, there's a plan to change the field `<User>.name` to `<User>.displayName`.
We can add the attribute `@map("display_name")` to commit this change to the database.
 
As most of us with Prisma knowledge know, we still use `.displayName` in the schema and Prisma Client. But `display_name` would be used in the database instead.

### `@@map` 
This is very similar to the `@map` attribute. However, with [`@@map`](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#map-1), we map the model name to its respective database table name to follow the `snake_case` standard.

We currently have a `User` model defined. Following this standard, we can place `@@map("users")` at the end of the model to prepare to commit these changes.

These are the conventions I have in mind right now. As the repo progresses, I'll watch for changes to the schema!

> Reference: [Prisma schema reference](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference)

**Comment by Ragudos** [comment]
Right, I forgot about the names having to be snake_case in Prisma, that's my bad. I'll keep that in mind!

**Comment by benjokazooiee** [comment]
I just got this done. Working on pulling.

**Comment by benjokazooiee** [comment]
This has been merged and can be closed.
