### ISSUE TITLE
[BUG]: ui: current race results 

### ISSUE THREAD

**Issue by scape76** [webdevcody/code-racer#396]
### Description

![image](https://github.com/webdevcody/code-racer/assets/87383867/fc4e8071-1918-4e25-afcc-0ead9aba7b19)
It looks a bit off when the snippet is long 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by scape76** [comment]
@AVAniketh0905 do you want to work on this?

**Comment by AVAniketh0905** [comment]
yes
