### ISSUE TITLE
[BUG]: Attempted import error warning

### ISSUE THREAD

**Issue by suti1979** [webdevcody/code-racer#399]
### Description

Build warning because of React client (useState, useEffect) import on server component.

```
 - warn ./src/components/ui/use-toast.ts
Attempted import error: 'useState' is not exported from 'react' (imported as 'React').

Import trace for requested module:
./src/components/ui/use-toast.ts
./src/lib/utils.ts
./src/app/layout.tsx
```

### (optional) What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by suti1979** [comment]
Working on it

**Comment by plbstl** [comment]
@suti1979 
in `src/components/ui/use-toast.ts`, try importing useState and useEffect directly from react, rather than using React.useState

**Comment by sudo-adduser-jordan** [comment]
This issue can be marked as closed.
