### ISSUE TITLE
Work on CONTRIBUTING.md

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/code-racer#4]
having a CONTRIBUTING.md file to help beginners understand the process of forking the repo, making branches, changing files on their branch, then making a pull request would be useful.  I can later make a video explaining this concept if needed.

We'd also want to explain how you can sync your fork with the upstream repo so that as other people make changes, your fork will get those changes.

**Comment by VoidedName** [comment]
+ link to it from readme.md
(+ maybe in a doc folder?)

**Comment by sudo-adduser-jordan** [comment]
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by sujeetgund** [comment]
I am looking forward to creating CONTRIBUTING.md for this project!
