### ISSUE TITLE
[FEATURE]: line numbers in the typing area

### ISSUE THREAD

**Issue by mshubitidze** [webdevcody/code-racer#401]
### Feature Summary

as a user it would be nice to have line numbers in the typing area
- line numbers should have a clear divider from the code
- current line number should be highlighted
- Extra: user should be able to choose either "normal" or "relative" either from a dropdown or a toggle
  - relative corresponds to relative line numbering
  - normal corresponds to normal line numbering

e.g. relative numbering:
<img width="1082" alt="Screenshot 2023-07-18 at 16 36 23" src="https://github.com/webdevcody/code-racer/assets/59510085/aea6630d-d4f0-42c7-9751-849371bd4416">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudo-adduser-jordan** [comment]
The merge above does not fully complete this issue. Feel free to contribute to this feature.
The line should also be highlighted along with the number horizontally, but not vertically.
Also, it does not highlight the number the cursor is on but only the last input index.
This should be impelemented  before the bonus feature.

**Comment by sudo-adduser-jordan** [comment]
Highlighting the line along with the number may be visually distracting. Impelement this feature commented out so we can test each functionality easily.
