### ISSUE TITLE
[BUG]: Search Params causing crashes

### ISSUE THREAD

**Issue by phoukiethseng** [webdevcody/code-racer#407]
### Description

Link causing crash: https://code-racer-eight.vercel.app/leaderboard?page=1&sort=takenTime.asc

<img width="1680" alt="image" src="https://github.com/webdevcody/code-racer/assets/57098413/5d73dd7c-0966-48a6-acfe-c0b9bd6afb95">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AVAniketh0905** [comment]
could you also add this
<img width="960" alt="bug-idk" src="https://github.com/webdevcody/code-racer/assets/95468529/497a9fbd-1dc0-4843-b532-ca5f902a88e1">

**Comment by scape76** [comment]
> could you also add this <img alt="bug-idk" width="960" src="https://user-images.githubusercontent.com/95468529/254326675-497a9fbd-1dc0-4843-b532-ca5f902a88e1.png">

I think I just fixed this
