### ISSUE TITLE
[BUG]: Leaderboard data not updated after race

### ISSUE THREAD

**Issue by joesabbagh1** [webdevcody/code-racer#415]
### Description

If you click on leaderboard after you finish the race, you wont get the updated data, you'll have to refresh.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joesabbagh1** [comment]
I'll work on this

**Comment by joesabbagh1** [comment]
I couldn't solve this bug, so feel free to try to fix it

**Comment by sudo-adduser-jordan** [comment]
Does this issue occur locally or in production?

I am not getting this issue locally.

**Comment by joesabbagh1** [comment]
locally, maybe its only happening to me? are you sure its working for you? check the races played before and after you finish the race, it should stay the same, and then refresh, should get updated. Same with cpm and accuracy

**Comment by sudo-adduser-jordan** [comment]
I'm not able to reproduce it locally

**Comment by joesabbagh1** [comment]
https://github.com/webdevcody/code-racer/assets/70956839/cf2fcd77-de94-462d-be16-2bf0d516830b

i tried using a different browser too

**Comment by sudo-adduser-jordan** [comment]
Yeah, that's what I did too. Try deleteing your project. Make sure your fork is updated. Wipe docker. I will try again to reproduce.

**Comment by joesabbagh1** [comment]
yeah its working fine now, i guess it was fixed during refactoring. Still weird bug
