### ISSUE TITLE
[BUG]: Pressing the Enter button when it is not a newline makes too many text errors

### ISSUE THREAD

**Issue by JKal24** [webdevcody/code-racer#437]
### Description

When the 'Enter' key is pressed and it isn't a newline, the game handles this as jumping to the next available newline and leaving all skipped letters as errors in the text that must be fixed. This heavily impacts a user's score as a result.

Please see video for reference.

Ideally the 'Enter' key should just be considered as a single entered character and should only produce 1 text error. 

https://github.com/webdevcody/code-racer/assets/64496022/9d6e10e6-fdd6-4815-b1c0-8e117493f86b

### (optional) What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JKal24** [comment]
I'll work on this.

**Comment by sudo-adduser-jordan** [comment]
This issue will also close #186
