### ISSUE TITLE
[TASK]: Add discord link in footer

### ISSUE THREAD

**Issue by Littletonconnor** [webdevcody/code-racer#438]
### Task Summary

Hello 👋 , i'm new to the community and found it a bit hard to find where the discord server was hosted at. 

I think it could be useful to have this as a link somewhere in the footer like so:

<img width="861" alt="Screenshot 2023-07-19 at 9 42 13 PM" src="https://github.com/webdevcody/code-racer/assets/26093912/5a1f5bcf-c18f-4fa6-9d68-1654803eacea">

Happy to submit a PR for this if folks agree!

**Comment by AlparslanAbdikoglu** [comment]
Sounds good!

**Comment by webdevcody** [comment]
could you actually add this to the left side of the footer next to the "Built by Cody & his **discord** community"
