### ISSUE TITLE
[FEATURE]:  Add setup script

### ISSUE THREAD

**Issue by Littletonconnor** [webdevcody/code-racer#439]
### Feature Summary

I'll admit, right now the setup instructions are super straightforward.  However over time they will probably evolve to a point where we'll want a setup script for newcomers to easily get setup.

I think it could be useful to create a setup script that just does all these things for us:

1. Ensures you have the correct minimum node version.
2. Ensures you have the correct minimum docker version.
3. Installed dependencies (This is not currently included in the readme but technically required)
4. (Maybe) auto rename env.example for users?
5. This script would already be setup and ready to include any other pre-reqs that get introduced later down the line.

I'd be happy to work on this if people think this would be useful. I have a couple questions if we do want to move forward with it though:

1. What minimum version of docker do we want to support?
6. What minimum version of node do we want to support?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Littletonconnor** [comment]
Okay cool. I plan to pick this up early next week 👍

**Comment by AlparslanAbdikoglu** [comment]
@Littletonconnor  hey check out nvm ( node version manager ) should help you get started with the script

**Comment by Littletonconnor** [comment]
Thanks for the suggestion, I didn't want to include nvm in the setup script, but I did add it to the README.
