### ISSUE TITLE
[TASK]: Create component for user infomation

### ISSUE THREAD

**Issue by liamsegura** [webdevcody/code-racer#45]
### Task Summary

Can i be assigned to this, as i believe this will be a reusable component.

### Acceptance criteria

- [ ] User information is moved into a separate component

**Comment by webdevcody** [comment]
@liamsegura what's your name on discord.  I'm not sure what this issue is addressing.  We shouldn't be creating reusable components unless we actually know where they will be reused.  What page would this be displayed on?

**Comment by liamsegura** [comment]
> @liamsegura what's your name on discord. I'm not sure what this issue is addressing. We shouldn't be creating reusable components unless we actually know where they will be reused. What page would this be displayed on?

I am “person” on discord

Going to close this issue as the user info I was referencing will now most likely be placed within the header component and shouldn’t need a separate component
