### ISSUE TITLE
[FEATURE]: Show Overall ranking of a user

### ISSUE THREAD

**Issue by Ragudos** [webdevcody/code-racer#475]
### Feature Summary

So, it would be nice to show a user their overall ranking in the leaderboard page to quickly know and not browse the table just for that knowledge.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ragudos** [comment]
will work on this

**Comment by scape76** [comment]
hey, @Ragudos are you still working on this?

**Comment by Ragudos** [comment]
Hello, yes, I tried it yesterday but I can't seem to find a way to do it. The array is returning empty when I do.

const currentPlace = arrayOfUserdInLeaderboard.filter((user, index) => {
 return user.id === currentUser.id ? index : null
})

With this, I planned to get the index of the user and that would be their current place.

If someone plans to do this, then I'll gladly give it to them as I've been busy lately with my upcoming academic stuff

**Comment by Ragudos** [comment]
Since there is a statement that you must race 5 times to have a ranking

**Comment by scape76** [comment]
Yes, the leaderboard shows only the ones who has 5 races at least, but it also makes the db query depending on a current page. In your case you will need to make a query for **all** of the users with 5 races at least.
