### ISSUE TITLE
.env.example missing variable

### ISSUE THREAD

**Issue by BlakeLawrence** [webdevcody/code-racer#481]
- ran into this error when running npm run dev:

     ![image](https://github.com/webdevcody/code-racer/assets/68634122/6a48bcdd-4160-40bb-9846-78ec08539772)

Adding the following to the .env file sorts the issue:
```
 MULTIPLAYER= true
```

Just wanted to flag it up.

**Comment by BlakeLawrence** [comment]
I am not sure if adding MULTIPLAYER = true to the .env.example would be a best practice approach, but if so, I'd be happy to make the change.

**Comment by greidinger-reis** [comment]
What would you say is a better way to do this feature flag?

**Comment by BlakeLawrence** [comment]
Oh sorry, didn't see that, my apologies. I was just flagging an issue I noticed that someone in discord helped me with. I will close issue
