### ISSUE TITLE
[FEATURE]: Better multiplayer race UI

### ISSUE THREAD

**Issue by greidinger-reis** [webdevcody/code-racer#486]
### Feature Summary

I haven't put much work in making the multiplayer UI look good.
Any contributions are appreciated.

Currently:
- Waiting screen:
![image](https://github.com/greidinger-reis/code-racer/assets/62309738/e5ac0d4f-7fce-4506-a8f4-2651ef641cdf)
- Countdown screen:
![image](https://github.com/greidinger-reis/code-racer/assets/62309738/6cda2a98-8f23-4b77-b48d-e9399ce1c727)
- Loading results:
![image](https://github.com/greidinger-reis/code-racer/assets/62309738/ad596e27-5d60-4dc8-b14c-400242e8236b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nassorc** [comment]
Can I work on this?

**Comment by greidinger-reis** [comment]
> Can I work on this?

yes, go ahead.
