### ISSUE TITLE
[TASK]:  How to Set up `DATABASE_URL` details in `README.md` or `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by Akarikev** [webdevcody/code-racer#49]
### Task Summary

can someone please write on how to set up the `DATABASE_URL` from postgres in either the `README.md` or `CONTRIBUTING.md` so that those now joining can easily set up the project and start working on the project on their dev servers 

### Acceptance criteria

- [ ] [DONE IN READ.ME]
- [ ] [DONE IN CONTRIBUTING.md]

**Comment by sudo-adduser-jordan** [comment]
This information is already available in those resources. Please take the time to understand the provided information before opening issues. This issue should marked as closed.

**Comment by Akarikev** [comment]
alright thanks, but, I only see that the information was only available for docker spin, but, I thought it might be helpful if someone who has postgres installed on their pc would just get the `DATABASE_URL` set up easily with the instructions provided. Thanks for the update 💯

**Comment by Akarikev** [comment]
> This information is already available in those resources. Please take the time to understand the provided information before opening issues. This issue should marked as closed. 

alright thanks, but, I only see that the information was only available for docker spin, but, I thought it might be helpful if someone who has postgres installed on their pc would just get the `DATABASE_URL` set up easily with the instructions provided. Thanks for the update 💯
