### ISSUE TITLE
Initial Work on README.md

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/code-racer#5]
We should update the readme to have a link to this discord, any videos on my youtube channel that document the progress of this community project (or videos that help explain concepts like forking, collab, etc).

The readme should explain the overall goals of the project, the choice in tech stack, how to contribute (link to CONTRIBUTING.MD file), and any pre-reqs that might be needed to get this project running.

**Comment by VoidedName** [comment]
Link to discrod is still missing
PR rules are missing

**Comment by BrunchWithYou** [comment]
I had some initial trouble spinning up the project with docker/db/env stuff, I'll work on adding more info onto the getting started or configuration so maybe it can help other beginners.
