### ISSUE TITLE
[TASK]: Authentication middleware

### ISSUE THREAD

**Issue by acollierr17** [webdevcody/code-racer#50]
### Task Summary

Next Auth's middleware should be implemented to protect frontend and backend API routes.

### Acceptance criteria

- [ ] The creation of `src/middleware.ts` and exporting `next-auth/middleware` from that file
- [ ] Applying the middleware on respective paths (ex., dashboard, and backend API routes)

### Any Additional Context

> References
- [Next Auth middleware](https://next-auth.js.org/configuration/nextjs#prerequisites)
- [Next.js middleware](https://nextjs.org/docs/app/building-your-application/routing/middleware#matching-paths)

I can tackle this issue a bit later in the week with more time off. However, feel free to get started on this if anyone wishes!

**Comment by trace2798** [comment]
I will work on it
