### ISSUE TITLE
[BUG]: Test Progression Bar Overflow

### ISSUE THREAD

**Issue by LukasOSmith** [webdevcody/code-racer#532]
### Description

When typing out longer text on a 4k screen the test progression bar goes off the screen
![image](https://github.com/webdevcody/code-racer/assets/135868602/3af945e1-ef87-452a-a052-6ce7faeec08a)

### (optional) What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sycodes95** [comment]
i will give this a shot

**Comment by StevenChen0824** [comment]
I want to propose a solution.
Beside progress bar, add a % base number to indicate to finished rate.
When screen size is smaller than maybe md size screen, than only show % base indicator.
% number will provide better feedback on smaller screen and maybe on mobile.
