### ISSUE TITLE
[BUG]: Bottom Spacing for results page

### ISSUE THREAD

**Issue by Abdelmuttalib** [webdevcody/code-racer#536]
### Description

This is a UI issue in the results page where the results page doesn't have a bottom spacing that separates it and gives room for the results actions to be scrollable and easy to see especially when the code block size is taking more height then the actions below it will be kinda hard to see especially that it will be so close to the page footer, image below shows this UI issue.

issue: 
![Screenshot from 2023-07-26 22-18-09](https://github.com/webdevcody/code-racer/assets/54845047/04f735d9-b753-48e4-af2f-2c3760d0f425)

fix:
![Screenshot 2023-07-26 at 23-10-08 CodeRacer](https://github.com/webdevcody/code-racer/assets/54845047/954de21f-ca42-46cb-9734-9247e9cb5757)

### (optional) What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Abdelmuttalib** [comment]
created PR https://github.com/webdevcody/code-racer/pull/538

**Comment by vignesh-gupta** [comment]
@Abdelmuttalib since the PR is merged pls close the issue
