### ISSUE TITLE
[BUG]: No Horizontal Scroll if the text overflows the text box

### ISSUE THREAD

**Issue by Sarath191181208** [webdevcody/code-racer#599]
### Description

I uploaded a new python snippet the snippet goes as follows 
```python
@pytest.mark.asyncio⏎
@pytest.mark.parametrize("username, password", username_password_list)⏎
async def test_all_details(username, password):⏎
    async with aiohttp.ClientSession() as sess:⏎
        user_name = await generate_session(username, password, sess)⏎
        if user_name is None:⏎
            assert False, "Login Failed!"⏎
        all_details = await get_all_details(sess, user_name)⏎
⏎
        for k, v in all_details.items():⏎
            assert v is not None or len(v) == 0 , f"Failed to get {k}"
```

I have a relatively small laptop display and what happened is that when i was typing the horizontal scroll didn't work.
What can we do to fix this problem: 
- turn auto wrap on for the text box. 
- make it auto scroll if the text isn't visible and we are typing it.

### (optional) What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AmanRoy007** [comment]
Hi @Sarath191181208  Could you please just elaborate more regarding this issue , Is it related with some kind of frontend UI issue , if you can post a screenshot of it , then it will be very helpful.

**Comment by AmanRoy007** [comment]
can I work on this @Sarath191181208 ?

**Comment by shashankbhatgs** [comment]
@AmanRoy007 I faced the same issue, and here's a snapshot of what the issue meant
![image](https://github.com/webdevcody/code-racer/assets/76593166/b69ccb5d-2ee7-4fa2-938f-934450b84f84)
After I typed the word "range", it should have automatically scrolled right side to show the rest of the sentence but it didn't. I have to manually drag the scroll bar at the bottom to view the rest of the sentence, which shouldn't be the case and should be done automatically as I type.

**Comment by AmanRoy007** [comment]
@shashankbhatgs Got it , We have to implement some kind of mechanism that it should auto scroll in text box while typing the code based on length.

**Comment by shashankbhatgs** [comment]
@AmanRoy007 Yeah I think that's what @Sarath191181208 meant. Please correct me if I'm wrong. 
Also, I just wanted to give clarity on the issue with ss, and to work on it you can ask @Sarath191181208

**Comment by AmanRoy007** [comment]
@shashankbhatgs  correct bro , I also want to solve this I have figured out one way also how to solve , may be we can solve it together.

**Comment by AmanRoy007** [comment]
With text-wrap:wrap we can solve this issue but you can see in below ss UI look a bit weird if we trying to wrap the text there is a lot of space pending after sentence.
![image](https://github.com/webdevcody/code-racer/assets/87869121/ee4079a9-98ed-44a4-b90f-9292c8b1ee38)

**Comment by carlosonrails** [comment]
Hey. Good guess @AmanRoy007. I'm doing my first contribution. I'd want to help you guys with that. @AmanRoy007 Did you implemented that already?

**Comment by Sarath191181208** [comment]
@AmanRoy007 That is exactly the issue I faced.

**Comment by AmanRoy007** [comment]
@carlosonrails  I didn't implemented that actually What I am thinking In the application Input is used to write the code if we change the input to textarea maybe it can resolved automatically

**Comment by AmanRoy007** [comment]
@Sarath191181208 , @shashankbhatgs  and @carlosonrails  I have raised a PR for above issue , You can check the fix and let me know if there are any chances it will break.

**Comment by AmanRoy007** [comment]
@scape76  you can see some ss of those type of snippets

**Comment by scape76** [comment]
It can't be fixed just with css, at the end of the line it expects a space, and that's confusing. Id personally consider this snippet as a bad one and reported it.

**Comment by scape76** [comment]
Otherwise an autoscroll is a better solution

**Comment by phoukiethseng** [comment]
> It can't be fixed just with css, at the end of the line it expects a space, and that's confusing. Id personally consider this snippet as a bad one and reported it.

We could set character limit per line in add-snippet page

**Comment by sohara** [comment]
I also experience this issue with typescript snippets. As @Sarath191181208 described, the next character towards the end of a long line of code can be hidden beyond the currently visible scroll area. I need to stop typing, scroll to the right, finish typing the line and hit return, then stop typing and scroll to the left so I can see the beginning of the now current line. Screenshot for reference.

![Screenshot 2023-08-13 at 3 33 38 PM](https://github.com/webdevcody/code-racer/assets/172627/628f3f0e-8fef-497f-91c1-35cf94077216)

**Comment by Aadeshcode** [comment]
I have managed to solve the problem but it would have been much efficient if the design is changed a little. like there is no need to be able to hit backspace once you have typed in the correct code and also if a user types an incorrect word the cursor need not move forward, rather it can just highlight the current cursor position in red. These are simple changes but can be efficient and will also help to solve this bug. 

Setting character limit per line might not be an efficient solution. Also simple CSS wont work as we are not working with an input element's cursor. The yellow cursor is our custom cursor.  

The way i have tried to solve it is by creating a window. Lets say max number of characters that can fit the pre tag in a line is 60, so in that case i have created a window of 0-55. once the character input reaches 55, i can manually scroll the pre tag using scrollBy method and also update the window from 0-55 to 1-56 and so on. that way i can know where is my cursor position. when backspacing, i can also look at the lower limit of the window, lets say we are on a window of 10-65, in this case our cursor will probably be in 60th character. When a user backspaces, the window will remain same i.e.10-65 , when the user reaches 15the element i can again use the scrollBy method to backspace, and also edit the window from 9-64 and so on. 
But all this would be redundant if the backspace is disabled. There is no use of backspace.

**Comment by Aadeshcode** [comment]
https://github.com/webdevcody/code-racer/assets/66826040/07075dc5-00f8-4071-b9e2-2a444d9982d0
Here is what i meant. 
Notice that the cursor doesn't move forward when the user types a wrong word. and the backspace doesnt work as there is no need to backspace.
The only issue is if the user manually scrolls it, auto scrolling breaks. there might be some workaround.
Please let me know what do you guys think!!

**Comment by scape76** [comment]
> https://github.com/webdevcody/code-racer/assets/66826040/07075dc5-00f8-4071-b9e2-2a444d9982d0 Here is what i meant. Notice that the cursor doesn't move forward when the user types a wrong word. and the backspace doesnt work as there is no need to backspace. The only issue is if the user manually scrolls it, auto scrolling breaks. there might be some workaround. Please let me know what do you guys think!!
What about hiding the scrollbar? So user wont be able to scroll manually, plus it will make no sense to let them do this.

**Comment by Aadeshcode** [comment]
> > https://github.com/webdevcody/code-racer/assets/66826040/07075dc5-00f8-4071-b9e2-2a444d9982d0 Here is what i meant. Notice that the cursor doesn't move forward when the user types a wrong word. and the backspace doesnt work as there is no need to backspace. The only issue is if the user manually scrolls it, auto scrolling breaks. there might be some workaround. Please let me know what do you guys think!!
> > What about hiding the scrollbar? So user wont be able to scroll manually, plus it will make no sense to let them do this.

@scape76 Exactly what i was thinking.

**Comment by romiljain5** [comment]
Can't we wrap content instead of auto scrolling

**Comment by Blankeos** [comment]
I feel like autoscrolling would be better tbh.
![image](https://github.com/webdevcody/code-racer/assets/38070918/04c8e9a3-6b55-48e1-8a65-cd1b86f963ba)
