### ISSUE TITLE
Login Capabilities

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/code-racer#6]
A user shall be able to register using github authentication so that as they complete races, their stats are tracked.

AC:
- a user can click a sign in button
- once the user signs in, they have the ability to sign out
- a profile avatar shall be present in the header when the user is signed in

**Comment by VoidedName** [comment]
What's backing the user identities? Oauth / openid? Self managed? Other?

**Comment by acollierr17** [comment]
> What's backing the user identities? Oauth / openid? Self managed? Other?

Per the [README](https://github.com/webdevcody/code-racer/blob/0ad8a4258467e55ff9d81d7e3da316a519cbcd67/README.md) and [`src/app/api/auth/[...nextauth]/route.ts`](https://github.com/webdevcody/code-racer/blob/0ad8a4258467e55ff9d81d7e3da316a519cbcd67/src/app/api/auth/%5B...nextauth%5D/route.ts), it looks like it's [GitHub OAuth 2.0](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps) with [NextAuth](https://next-auth.js.org/providers/github).
https://github.com/webdevcody/code-racer/blob/0ad8a4258467e55ff9d81d7e3da316a519cbcd67/src/app/api/auth/%5B...nextauth%5D/route.ts#L6-L9

**Comment by VoidedName** [comment]
That's just something someone did (after the question). NextAuth supports credential flow as well. This is more a decision to be taken by the PO (i.e. web dev)
