### ISSUE TITLE
[BUG]: Iterative key presses not reflecting to editor and all keys become blocked and app freezes.

### ISSUE THREAD

**Issue by devhiko** [webdevcody/code-racer#623]
### Description

When some unauthorized user opens the race page, and tries to start a new practice with random language and tries to pressing same key x2, app crashes and all other keys are being disabled at all. Backspace or space not working as in normal text editors to remove line or edit char.

Steps to reproduce: 
1. Open app, select 'Practice' with Go language, and try to make mistakes when writing code.
![a](https://github.com/webdevcody/code-racer/assets/99843102/4737f1be-1ed3-485b-a1cd-b6e29db61539)

### (optional) What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudo-adduser-jordan** [comment]
Are you able to backspace the invalid character?

Current functionally locks further input and allows backspace. This being an accuracy test, we are currently not planning on implementing text editor or LSP functionality.

**Comment by devhiko** [comment]
No, none of keys are not working when I make some typo this breaks me cuz i
couldn't finish race at all. I don't want advanced text editor features,
there is no need tho. I am only looking why it's locking and freezing at
one mistake, it behaving same when i press enter twice or more

31 Tem 2023 Pzt 22:16 tarihinde jordan ***@***.***> şunu
yazdı:

**Comment by Ragudos** [comment]
Yes. Please check if you can still remove the mistake and continue on typing. We actually tried to make it feel a little bit like an editor, but it became complicated. So, we just made it so a user is unable to type unless they correct a typo error. We should focus on solidifying the app's functionalities first (rankings, replays, multiplayers, achievements, snippet validation, etc.), and a simple typing interface is enough for now.

**Comment by Ragudos** [comment]
Are you unable to Backspace?

**Comment by devhiko** [comment]
I think we need some kinda group chat to discuss it, cuz this is the core
feature of app and it's not working anyhow. Maybe everything is perfect for
logged in users but, .. people want to try features and sometimes only need
is walking thru the app :)

31 Tem 2023 Pzt 22:56 tarihinde Aaron ***@***.***> şunu yazdı:

**Comment by devhiko** [comment]
Wish same, but neither I can fix my typo or continue to race with ignoring
mistakes to give a result at least.

31 Tem 2023 Pzt 22:56 tarihinde Aaron ***@***.***> şunu yazdı:

**Comment by devhiko** [comment]
Yep, at first mistake i am feeling like my keyboard disconnected :)

31 Tem 2023 Pzt 22:57 tarihinde Aaron ***@***.***> şunu yazdı:

**Comment by Ragudos** [comment]
I see. You'd like to be able to just continue on typing despite having mistakes/typo errors. However, the current app does not finish if an error exists, so the current functionality of stopping a user from typing is intended and not a bug in this context. I do agree somewhat with you, so maybe we can raise this concern as a feature and talk with others, specially Cody, regarding this.

**Comment by Ragudos** [comment]
Or perhaps show to a user a message that they are unable to type unless they correct their mistake. (a hint perhaps like, "Please press Backspace")

**Comment by sudo-adduser-jordan** [comment]
What keyboard do you use? Do you use a special keyboard layout or language?

Could you please console log the key input locally? Please include a picture of the log output.

**Comment by devhiko** [comment]
Yep, i am totally on this, this is all i have now. Maybe a error message at top like 'You made typo, please fix it via pressing backspace, and i think some "how to play" card, at top of page will be benefical like this image: :D 'd be enjoying maybe 
![kathryn-raccuglia-how-to-play-layout-01](https://github.com/webdevcody/code-racer/assets/99843102/f604cd21-648d-4b96-9da6-86ce41555519)

**Comment by devhiko** [comment]
> What keyboard do you use? Do you use a special keyboard layout or language?: 
- I realized "Backspace" is working on both and if this was intentional, everything is okay then.
We can close this, or maybe discuss on 'continue despite of mistakes and see everything at end. like quiz apps, at result dashboard some kinda thing like: 
[mistakes] [time] etc.
      3        1m 3s
