### ISSUE TITLE
[TASK]: Create seed for local script [E2E]

### ISSUE THREAD

**Issue by Wirblewind** [webdevcody/code-racer#624]
### Task Summary

I am currently "blocked" at working on leaderboard tasks (I have made the PR and commented out the code that is currently blocked/possible), as there is no data for the leaderboard to test with locally.

As pointed out by @sudo-adduser-jordan, a seed that only loads with a local script would be helpful.

**Comment by christianlozano99** [comment]
Has this been worked on? If I understand right it seems like it would be a script to have dummy data on the leaderboards to work with if so I can start looking into it.

**Comment by sudo-adduser-jordan** [comment]
That is correct. 

Nobody is currenlty working on this issue. Leave a comment saying that you will be working on it.

**Comment by christianlozano99** [comment]
Great, I'll try to have this done by the end of this week!
