### ISSUE TITLE
[BUG]: Replay not playing for unauthorized users

### ISSUE THREAD

**Issue by devhiko** [webdevcody/code-racer#625]
### Description

After finishing a race, replay is not working and i cant see anything playing on replay screen. I tried restarting replay but nothin happened, at console or somewhere am not seeing anything bad. On Chrome, i am not even seeing that replay controls on replay div.
![b](https://github.com/webdevcody/code-racer/assets/99843102/b3e12ee0-64b4-4fec-a866-c22067f74ef9)
Code results: 
![b1](https://github.com/webdevcody/code-racer/assets/99843102/b4231e82-8286-45c3-bbf7-ae23a01e529c)
Replay: (Chrome), even i flnished race without mistakes, it still showing my errors on replay and not playing after that error.
![b2](https://github.com/webdevcody/code-racer/assets/99843102/ba0b6177-0ecc-48f3-80ed-01c318dc8048)

### (optional) What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudo-adduser-jordan** [comment]
I am not recieving any replay errors on either browser. Can you try clearing out your cookies/cache?

Those code results are incorrect though. That needs a fix. I will open an issue.

**Comment by devhiko** [comment]
Weird, anytime I finished a race on both, i couldn't replay my progress.
Yeah, i finished without errors but it's showing some errors at replay. I
opened browser first time in inprivate mode and cache was cleared also.
I ll clone the codebase and try to achieve same things at dev, maybe I can
find something related. Thanks for your effort also.

31 Tem 2023 Pzt 21:40 tarihinde jordan ***@***.***> şunu
yazdı:

**Comment by devhiko** [comment]
Well, maybe. I think it's related with auth process, maybe things are not
working nice for normal users, or maybe editor, i ll tell you if I find
something weird. You know at some websites, some features not working
properly for unauthorized users.

31 Tem 2023 Pzt 22:10 tarihinde jordan ***@***.***> şunu
yazdı:

**Comment by sudo-adduser-jordan** [comment]
The chart results appear to be related to user authorization. The replay issue does not.

**Comment by devhiko** [comment]
Yeah I am on it, will try to understand what happens when race finished

31 Tem 2023 Pzt 22:18 tarihinde jordan ***@***.***> şunu
yazdı:

**Comment by devhiko** [comment]
@sudo-adduser-jordan So, you can close this also, looks like its working somehow.
