### ISSUE TITLE
[BUG]: Mobile Phone Keypad Is Not Recognized

### ISSUE THREAD

**Issue by Ragudos** [webdevcody/code-racer#627]
### Description

I'm not sure yet if we want to include mobile friendliness, but I have noticed this for awhile (just haven't submitted an issue yet), and the app's text input doesn't function properly on mobile (The input element is probably doing its job properly as my auto-correct/word suggestion is keeping track of what I type and is updating with each keypress). This is probably related to event listeners? Anyway, since I don't have the energy and time right now to look at our code, I'm just here to raise this concern. I'm using my phone's keypad / touchscreen keyboard

Brand:

OPPO Reno 5 5G

Device Specs:

Model - CPH2145
Processor - Qualcomm SDM765G 5G Octa-core
Android version - 13
Kernel version - 4.19.157-perf+

Video:

https://github.com/webdevcody/code-racer/assets/133567781/8fbea85d-4d71-46cf-a7f1-862b4d891237

### (optional) What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devhiko** [comment]
Phone keypads having 'autocomplete' so i think its kinda cheat and it shouldnt be an option to use website, maybe there is a way to prevent mobile devices from start 🤣

**Comment by sudo-adduser-jordan** [comment]
Good point. Easy fix `autocomplete="off"`

**Comment by Ragudos** [comment]
Oh no, I don't use the autocomplete, it only suggests words that the word I'm typing can be completed into (probably needed to word it differently).

**Comment by Ragudos** [comment]
I don't click the suggested words

**Comment by sudo-adduser-jordan** [comment]
I understand.

Currently working on IOS devices. `cursor-none` does not remove cursor on IOS.

**Comment by Ragudos** [comment]
so it depends on the OS, I guess. I'm currently just learning the ropes of coding on Android for convenience, and I think this can be debugged on Android (since I don't know how to emulate a keypad on desktop). Anyway, if this is not doable right now, feel free to close or block this issue for now, just a heads-up.

**Comment by devhiko** [comment]
You know what, i have actually i lot ideas to improve this, but when we do those it ll become a game and i m not sure if we want to build a game or not 😆

**Comment by sudo-adduser-jordan** [comment]
You can connect you moblie devices to localhost with some effort.
https://stackoverflow.com/questions/4779963/how-can-i-access-my-localhost-from-my-android-device

Another way to test is to make your best guess, then to push to production.

If there is an emulator for web developer tools or another tool please link it in this issue.

**Comment by devhiko** [comment]
I have kinda ideas like 'Piano Tiles' or 'Guitar Hero' logic but not sure if its lot complexity and dream or doable tbh, but if we do this, i m sure it ll become more enjoying and awesome. just place a keyboard image instead piano.
![maxresdefault](https://github.com/webdevcody/code-racer/assets/99843102/5ee04f51-d5a8-43d8-86f8-7774e29942ab)

**Comment by Ragudos** [comment]
Woah, I just tried it on phone and it worked! I didn't think of using the IP address even though I knew that localhost is using our local network. Thank you, sudo!!

**Comment by Ragudos** [comment]
I think it's better to try it solving first as nothing beats a good old in-built functionality

**Comment by Ragudos** [comment]
![image](https://github.com/webdevcody/code-racer/assets/133567781/d6da54ca-1ba1-4c61-bebb-60b18e8948c0)
So, mobile keyboards, a.k.a IME's says the internet actually returns "Unidentified" as the e.key for event listener of onKeyDown.

**Comment by Ragudos** [comment]
will implement a fix, assign me to this
