### ISSUE TITLE
[FEATURE]: `New Record` Notification

### ISSUE THREAD

**Issue by phoukiethseng** [webdevcody/code-racer#645]
### Feature Summary

Since now we have a notification system, as a user, I would like to be notified when I break a new personal record after finishing race.

User flow:
1. Start racing on snippet that user have practiced before
2. After finishing a race, if they break a new record, a notification should be push to them
3. When user click on that notification, it should redirect them to dashboard race section page
![image](https://github.com/webdevcody/code-racer/assets/57098413/148eaad1-d847-4d57-93f7-7af1b2c7c0c6)

For those who want to work on this, you can take a look at `packages/app/src/lib/notification.ts` file. You can use `pushNotification` server action to notify user. `ctaUrl` is the url to redirect user to when they click on notification

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christianlozano99** [comment]
@phoukiethseng Sounds like a nice feature I've been working on implementing. Do we want it to be a new record for only CPM or Accuracy, or do we want to push a notification for either?

**Comment by phoukiethseng** [comment]
> @phoukiethseng Sounds like a nice feature, I've been working on implementing it. Do we want it to be a new record for only CPM or Accuracy, or do we want to push a notification for either?

Both of them sound great to me. Also if you have any question about notification system, let's me know.👌
