### ISSUE TITLE
[BUG]: Start Race button not centered

### ISSUE THREAD

**Issue by enes-96** [webdevcody/code-racer#666]
### Description

When the window is resized to a width between 640 and 767 pixels, the "Start Race" button on the landing page is not properly centered. I think it could be fixed in hero-banner.tsx

### (optional) What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by enes-96** [comment]
![Screenshot 2023-08-07 at 15 18 26](https://github.com/webdevcody/code-racer/assets/111685648/2df8450b-3e64-4c61-b6b2-9528f41a62fb)

**Comment by sycodes95** [comment]
ill work on this
