### ISSUE TITLE
[BUG]: Long names on modal confirmation for user actions on settings in profile page is overflowing

### ISSUE THREAD

**Issue by Ragudos** [webdevcody/code-racer#668]
### Description

![image](https://github.com/webdevcody/code-racer/assets/133567781/32306b3e-aaca-4352-9d5c-d3ccd7cbf0c1)
![image](https://github.com/webdevcody/code-racer/assets/133567781/5cd7358a-ab37-4871-ad24-fc3eafe0792f)

- needs to not overflow

If anyone isn't assigned on this by August 9 (Wednesday), then I'll start fixing it. A bit busy again this past week.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by QuickerMaths** [comment]
I will work on that

**Comment by bkbCodes** [comment]
We can add something like type "DELETE"+ 3/4 digit opt. Instead of writing long usernames to confirm.
