### ISSUE TITLE
[BUG]: Overall additions and deletions count not working

### ISSUE THREAD

**Issue by FraneCaleta** [webdevcody/code-racer#678]
### Description

In _Contributors_ tab, number of lines that were added/deleted are not being counted.
Individual counts seem to still work, but overall changes are not.

![image](https://github.com/webdevcody/code-racer/assets/37557775/fc22e7f5-a146-42a0-abad-803c4d5a98d8)

### (optional) What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by viralgupta** [comment]
Additions and deletions are related to the current week (starting from Aug 13). The data is being sourced from the GitHub API, and there doesn't appear to be a calculation error.

**Comment by FraneCaleta** [comment]
Aha, I see... So that is the way we want to keep it? Only count weekly contributions and not overall?

**Comment by FraneCaleta** [comment]
Closed the issue for now. It can be re-opened if we decide to count overall contributions in the future.
