### ISSUE TITLE
[TASK]: Change readme badges

### ISSUE THREAD

**Issue by bruno-queiroz** [webdevcody/code-racer#686]
### Task Summary

Add good badges to the readme, like the license type, number of forks, these kinds of things.

I guess this could be a good issue for beginners to contribute to the project.

**Comment by romiljain5** [comment]
@bruno-queiroz Can I pick this, WIll create a pull request for same

**Comment by vignesh-gupta** [comment]
@romiljain5 seems like you just changed icons not the badges. I'll take up the badge work
