### ISSUE TITLE
[BUG]: The code on small screen needs to be scrolled horizontally

### ISSUE THREAD

**Issue by romiljain5** [webdevcody/code-racer#689]
### Description

When we try to write code in small screens, Like mac book ones the scrollbar appears at bottom and while typing user doesn't knows that what code resides on right hand side, He needs to scroll to be able to see

Solution 👍 
We can wrap the code and hide the overflow horizontally

Please suggest if you have some better idea

### (optional) What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bruno-queiroz** [comment]
I think we already have a issue for that, look at the #599 issue.

**Comment by romiljain5** [comment]
Oh ok, Closing this issue in that case
