### ISSUE TITLE
[FEATURE]: score screen

### ISSUE THREAD

**Issue by scape76** [webdevcody/code-racer#69]
### Feature Summary

As it was mentioned by Cody, in issue #7 , user wants to see his result as he finishes the race. 

### Acceptance criteria

- user has to be redirected by the end of the race
- user should see his taken time & number of errors for now
- non-auth users can also see the results
- has to be an intercepting route (and a page) with go back button

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mauryapari** [comment]
Hi @scape76. are you working on this?

**Comment by scape76** [comment]
> Hi @scape76. are you working on this?

No, Im not

**Comment by webdevcody** [comment]
someone worked on this, good enough for now
