### ISSUE TITLE
[BUG]: Hovering on Achievement Progress creates a glitching animation

### ISSUE THREAD

**Issue by mikah13** [webdevcody/code-racer#699]
### Description

URL:
https://code-racer-eight.vercel.app/dashboard/awards

Hovering my mouse at the bottom edge of the Achievement Progress button keeps the component bouncing infinitely

### (optional) What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mikah13** [comment]
infinite loop definitely sounds like a great idea, I think it fits with the theme of a racing game too 

https://codepen.io/ has a cool transition when you hover on the start coding button

https://codepen.io/onthreat/pen/wvRKBRv this is me trying to recreate that same effect

**Comment by QuickerMaths** [comment]
Thats looking really solid in my opinion, would you mind if I implement this?

**Comment by mikah13** [comment]
yes please go ahead
