### ISSUE TITLE
Starting a Race

### ISSUE THREAD

**Issue by webdevcody** [webdevcody/code-racer#7]
As a guest, I should be able to start a race which will show me a hard coded snippet of typescript.  I should be able to type the snippet and see a cursor move over the typed words making their color green / red as I type them.  After finishing the entire snippet, I should be sent to a score screen that shows how many I got correct or wrong, how fast I typed, and what place I finished in the race.

AC:
- a user has a way to start a race
- a user has a way to view and type a typescript snippet of code
- once the user types to the end of the snippet, they should be navigated to a score screen
- a user can "race again" after seeing the score screen

**Comment by ixtk** [comment]
Possible initial UI mockup that allows vertical space with race visualization. We could also use horizontal space for something though.

![initial-ui](https://github.com/webdevcody/code-racer/assets/62815655/a5d74841-9d01-4ea0-ab72-88f3531b27be)

**Comment by KaiBelmo** [comment]
working on this

**Comment by nelsonfrz** [comment]
I would recommend to align the race visualization left to the code input as code is more vertical by nature.

Here is a mockup that describes it better:
![Image](https://github.com/webdevcody/code-racer/assets/117679845/f221c739-3496-4049-8b34-053277022958)

**Comment by webdevcody** [comment]
good enough
