### ISSUE TITLE
[BUG]: PB history table has a duplicate snippet column

### ISSUE THREAD

**Issue by LukasOSmith** [webdevcody/code-racer#709]
### Description

when I went to the dashboard and I tried to remove the "name" column because it didn't have anything in it. the column kept duplicating itself when I tried to toggle it. 

![image](https://github.com/webdevcody/code-racer/assets/135868602/7394c631-ffd8-4478-b6e1-2ae376516836)

### (optional) What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by omarnazih** [comment]
@LukasOSmith Bug Solved, @codyseibert check PR please.

**Comment by omarnazih** [comment]
@webdevcody Bug is fixed, I think you can close this issue
