### ISSUE TITLE
[BUG]: Inability to Correct Typos on Last Line During Code Races

### ISSUE THREAD

**Issue by am79041** [webdevcody/code-racer#714]
### Description

When participating in code races , there is a problem that prevents users from correcting a typo on the last line of a code snippet. If the user accidentally presses the Enter key at the end of the snippet, there is no way to navigate back to the last line to make corrections. As a result, the user is forced to restart the race.

![Screenshot from 2023-09-10 10-23-09](https://github.com/webdevcody/code-racer/assets/70338712/ce680c9c-8ef3-4ac9-9bb6-40a9a856a54a)

### (optional) What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kumaramit3** [comment]
You can navigate through typos with the help of backspace.
