### ISSUE TITLE
[BUG]: Biography on Profile page is marked as Mandatory with (*) but it isn't mandatory.

### ISSUE THREAD

**Issue by bmonish** [webdevcody/code-racer#724]
### Description

![image](https://github.com/webdevcody/code-racer/assets/31185862/43c98a84-6154-4f7c-9c22-074cfc658f85)

Either we should remove the * or make the field mandatory/

### (optional) What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bmonish** [comment]
If possible, I would like to work on this issue! It will help me get started with Next.Js

**Comment by Cosmin29** [comment]
> If possible, I would like to work on this issue! It will help me get started with Next.Js

Did you manage to solve the bug?

**Comment by bmonish** [comment]
Yes! I'm assuming the Biography isn't mandatory. So, I'm removing the * symbol.

**Comment by bmonish** [comment]
@Cosmin29 Can you take a look at the PR?

**Comment by Cosmin29** [comment]
@bmonish I think it's okay. Biography only had that (*). I thought it was a "required" attribute in the code. I'm looking for future bugs or new features because I'm learning next.js too.^^
