### ISSUE TITLE
[BUG]: Cannot practice race

### ISSUE THREAD

**Issue by ParadigmMango2** [webdevcody/code-racer#745]
### Description

On the main website, I cannot practice race.
![image](https://github.com/webdevcody/code-racer/assets/157170222/ca6e9371-ba12-4c6d-9cc4-6e7e71448bba)

The debugger window on my browser shows this issue:
![image](https://github.com/webdevcody/code-racer/assets/157170222/b5d50b0a-329d-4573-a1b1-c4d596a9056c)

When running my local instance of Code Racer, I do not have this problem.

### (optional) What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TyrinH** [comment]
This is resolved
