### ISSUE TITLE
[BUG]: Cannot Login

### ISSUE THREAD

**Issue by ParadigmMango2** [webdevcody/code-racer#746]
### Description

When logging in, I get to this page:
![image](https://github.com/webdevcody/code-racer/assets/157170222/9f20f926-5a36-4342-bec8-710024860f2c)

The page only gives a favicon error in the debugger and clicking "Sign in with GitHub" does nothing.
![image](https://github.com/webdevcody/code-racer/assets/157170222/57235101-c87a-4398-b716-4609a41ddd46)

### (optional) What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TyrinH** [comment]
This is resolved
