### ISSUE TITLE
[BUG]: Unable to Signing using GitHub 

### ISSUE THREAD

**Issue by farazalidev** [webdevcody/code-racer#755]
### Description

I am Unable to Signing using GitHub, If I have to sign up first then where is the button to signup.

![Screenshot from 2024-05-15 13-22-35](https://github.com/webdevcody/code-racer/assets/115402976/ea266f9a-5906-41e3-9480-3d60973c5678)

### (optional) What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farazalidev** [comment]
[Video Link](https://www.loom.com/share/b350f47f7d7f43d08ee2361b877daddc)

**Comment by RafaelZasas** [comment]
I'm having the same issue

**Comment by TyrinH** [comment]
This is resolved
