### ISSUE TITLE
[TASK]: Add badges to user's profile

### ISSUE THREAD

**Issue by Killbyfire** [webdevcody/code-racer#76]
### Task Summary

Just like discord has badges show achievements on the profile page of a user which will make it look nicer than on the dashboard.

### Acceptance criteria

- [] Display badges out of a list
- When hovering show the date it has been given to the user

**Comment by andyphl** [comment]
Hi @Killbyfire, are you working on this? Maybe I can try working on the task.

**Comment by Killbyfire** [comment]
Hey @andyphl , sorry for the late response but i am not working on this. Just opened a issue.

**Comment by vignesh-gupta** [comment]
@andyphl are you picking this one?

**Comment by webdevcody** [comment]
this seems done
