### ISSUE TITLE
[TASK]: User should be able to pick race emoji on user profile page

### ISSUE THREAD

**Issue by mauryapari** [webdevcody/code-racer#77]
### Task Summary

Make an option enabled on the profile page so that a user can pick a “race emoji”.
The emoji should also display when the user is participating in code races.

### Acceptance criteria

- Option should exist which allows the user to pick an emoji
- Emoji should be stored with the user's information

**Comment by mauryapari** [comment]
Assigning this to myself.

**Comment by Psypher1** [comment]
> Assigning this to myself.

Ah, you beat me to it.... Oh well, I'll snag the next one

**Comment by mauryapari** [comment]
Profile images could be used in place of Race emojis
