### ISSUE TITLE
[TASK]: Create share on Social Media Buttons

### ISSUE THREAD

**Issue by mauryapari** [webdevcody/code-racer#97]
### Task Summary

- Use existing reusable buttons to make social media buttons

### Acceptance criteria

- Should be able to share the stats to various platform

**Comment by mauryapari** [comment]
Assigning this to myself.

**Comment by mauryapari** [comment]
Putting this on hold as I have started to work on the landing page.
Anyone is free to work on this.

Thanks,

**Comment by AVAniketh0905** [comment]
I'm gonna take this up
